--QUERY 1
SELECT 
    NAME + "(" + UPPER(LEFT(OCCUPATION,1)) + ")"
FROM
    OCCUPATIONS
ORDER BY
    NAME

--QUERY 2
SELECT 
    'There are a total of ' + 
    CAST(COUNT(*) AS VARCHAR) + 
    ' ' + LOWER(OCCUPATION) + 's.' AS RESULTADO
FROM 
    OCCUPATIONS
GROUP BY 
    OCCUPATION
ORDER BY 
    CAST(COUNT(*) AS VARCHAR), OCCUPATION;
